### ISSUE TITLE
Upstream kernel !

### ISSUE THREAD

**Issue by SahilSonar** [BunsExynos/android_device_samsung_a5xelte#3]
Hey, I would suggest using latest upstream kernel

**Comment by dariotrombello** [comment]
What are you talking about? The kernel is already upstreamed to the latest version. It reached EOL so it doesn't get any further updates

```
VERSION = 3
PATCHLEVEL = 10
SUBLEVEL = 108
```

**Comment by SahilSonar** [comment]
Maybe something 3.18 never mind its okay

**Comment by dariotrombello** [comment]
You can't upstream a 3.10.x kernel to 3.18.x...

**Comment by SahilSonar** [comment]
You can do it, if you know making those drivers but its possible

**Comment by dariotrombello** [comment]
Yeah but that's called backporting. And why should @BunsExynos put so much effort in doing it? It runs perfectly on 3.10

**Comment by SahilSonar** [comment]
Yep backporting never mind it old... the thing I didn't see that 3.10 I saw it as 3.18 so ignore

**Comment by SahilSonar** [comment]
Hmm ... you are from Exynos community interesting
